import { SEO } from "@/components/SEO";

const Disclaimer = () => {
  return (
    <>
      <SEO
        title="Disclaimer - CodeHubMaster"
        description="Read CodeHubMaster's disclaimer regarding AI-generated content, educational resources, and limitations of liability."
        keywords="disclaimer, legal notice, AI content disclaimer, CodeHubMaster"
        canonical="https://codehubmaster.site/disclaimer"
      />

      <div className="min-h-screen bg-background py-12 px-4">
        <div className="container mx-auto max-w-4xl">
          <h1 className="text-4xl font-bold text-center mb-4 text-foreground">Disclaimer</h1>
          <p className="text-center text-muted-foreground mb-12">Last Updated: March 24, 2026</p>

          <div className="space-y-8 text-muted-foreground leading-relaxed">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">1. General Information</h2>
              <p>
                The information provided on CodeHubMaster (codehubmaster.site) is for general informational and educational purposes only. While we strive to keep the information accurate and up to date, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the website or the information, products, services, or related content contained on the website for any purpose.
              </p>
              <p className="mt-3">
                Any reliance you place on such information is strictly at your own risk. We strongly recommend that you verify any code, solutions, or technical guidance provided on this platform before using it in production environments or critical applications.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">2. AI-Generated Content Disclaimer</h2>
              <p>
                CodeHubMaster uses artificial intelligence technology, including large language models such as GPT-4, Claude, and Gemini, to generate educational content and answer programming questions. It is important to understand the following about AI-generated content on our platform:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li><strong className="text-foreground">Accuracy:</strong> AI-generated answers are based on patterns learned from training data and may not always be 100% accurate. While our AI achieves high accuracy rates, errors, outdated information, or incomplete responses may occasionally occur.</li>
                <li><strong className="text-foreground">Not Professional Advice:</strong> The content generated by our AI is not a substitute for professional programming advice, code review, or expert consultation. Always use your own judgment when applying AI-generated code in real projects.</li>
                <li><strong className="text-foreground">Verification Required:</strong> We encourage all users to independently verify AI-generated code and solutions, especially before deploying them in production environments, handling sensitive data, or integrating them into business-critical systems.</li>
                <li><strong className="text-foreground">Evolving Technology:</strong> AI technology is rapidly evolving, and the quality and accuracy of responses may vary over time as models are updated and improved.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">3. Educational Purpose Only</h2>
              <p>
                All content on CodeHubMaster, including articles, tutorials, guides, code examples, and AI-generated answers, is provided solely for educational and learning purposes. This content should not be treated as professional advice for:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li>Production-grade software development without proper testing and code review</li>
                <li>Security-sensitive applications without professional security auditing</li>
                <li>Financial, medical, legal, or other regulated domain applications</li>
                <li>Critical infrastructure or safety-critical systems</li>
              </ul>
              <p className="mt-3">
                Users are responsible for ensuring that any code or technical guidance obtained from our platform meets the specific requirements and quality standards of their projects. CodeHubMaster is a learning tool designed to help you understand programming concepts, not a replacement for thorough software development practices.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">4. No Guarantees on Results</h2>
              <p>
                While we showcase success stories and testimonials from our users, we do not guarantee that you will achieve specific results, learn at a certain pace, or obtain employment as a result of using our platform. Learning outcomes depend on many individual factors including prior experience, dedication, practice frequency, and the complexity of the topics studied.
              </p>
              <p className="mt-3">
                Any statistics, metrics, or performance indicators mentioned on our Site (such as response accuracy rates, user counts, or project numbers) are approximate and may change over time. These figures are provided for illustrative purposes and should not be interpreted as guaranteed outcomes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">5. External Links Disclaimer</h2>
              <p>
                Our website may contain links to external websites, tools, and resources that are not provided or maintained by CodeHubMaster. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. The inclusion of any links does not necessarily imply a recommendation or endorsement of the views expressed within them.
              </p>
              <p className="mt-3">
                We have no control over the content, privacy policies, or practices of any third-party websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party websites you visit.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">6. Limitation of Liability</h2>
              <p>
                In no event shall CodeHubMaster, its owners, authors, contributors, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or other intangible losses, resulting from:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li>Your access to, use of, or inability to access or use the Service</li>
                <li>Any conduct or content of any third party on the Service</li>
                <li>Any content obtained from the Service, including AI-generated code or answers</li>
                <li>Unauthorized access, use, or alteration of your transmissions or content</li>
                <li>Errors, bugs, or inaccuracies in AI-generated content or code examples</li>
                <li>Any damage to your computer system, loss of data, or other harm that results from your use of the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">7. Code Usage Disclaimer</h2>
              <p>
                Code examples, snippets, and solutions provided on CodeHubMaster are offered "as is" without any warranty. Before using any code from our platform, you should:
              </p>
              <ul className="list-disc list-inside ml-4 space-y-2 mt-3">
                <li>Test the code thoroughly in a safe development environment</li>
                <li>Review the code for security vulnerabilities and potential issues</li>
                <li>Adapt the code to meet your specific project requirements and coding standards</li>
                <li>Ensure compatibility with your technology stack and dependencies</li>
                <li>Follow your organization's code review and deployment procedures</li>
              </ul>
              <p className="mt-3">
                CodeHubMaster is not responsible for any issues, losses, or damages that may arise from using code found on our platform in your projects.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">8. Advertising Disclaimer</h2>
              <p>
                Our website displays advertisements through Google AdSense and potentially other advertising networks. These advertisements are served by third-party advertising companies and may use cookies to serve ads based on your browsing history and interests. The presence of advertisements on our Site does not constitute an endorsement or recommendation of the advertised products or services by CodeHubMaster.
              </p>
              <p className="mt-3">
                We are not responsible for the content, accuracy, or opinions expressed in advertisements displayed on our Site. Users should exercise their own judgment when interacting with advertisements and make purchasing decisions based on their own research.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">9. Intellectual Property</h2>
              <p>
                The original content, features, and functionality of CodeHubMaster are owned by CodeHubMaster and are protected by international copyright, trademark, and other intellectual property laws. Our articles, guides, tutorials, and educational content are original works created by the CodeHubMaster team.
              </p>
              <p className="mt-3">
                Users may reference and learn from our content for personal educational purposes. However, wholesale copying, reproduction, or redistribution of our content without prior written permission is prohibited. If you wish to use our content for commercial purposes, please contact us at support@codehubmaster.com.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">10. Changes to This Disclaimer</h2>
              <p>
                We reserve the right to modify this Disclaimer at any time without prior notice. Changes become effective immediately upon posting on this page. Your continued use of the Site after any modifications constitutes your acceptance of the updated Disclaimer. We encourage you to review this page periodically for any changes.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">11. Contact Information</h2>
              <p>If you have any questions about this Disclaimer, please contact us:</p>
              <div className="mt-3 bg-muted/50 p-6 rounded-lg">
                <p><strong className="text-foreground">CodeHubMaster</strong></p>
                <p className="mt-2">Email: <a href="mailto:support@codehubmaster.com" className="text-primary hover:underline">support@codehubmaster.com</a></p>
                <p className="mt-1">Website: <a href="https://codehubmaster.site" className="text-primary hover:underline">https://codehubmaster.site</a></p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default Disclaimer;
